version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - configure_project:
      - run: |
          echo $GCLOUD_SERVICE_KEY > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud services enable "compute.googleapis.com" --project="${GOOGLE_PROJECT_ID}"
          gcloud services enable "compute.googleapis.com" --project="${GOOGLE_PROJECT_ID}"
