version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Configure access
          command: |
            echo ${GCLOUD_SERVICE_KEY} > gcloud-key.json
            gcloud auth activate-service-account --key-file=gcloud-key.json
            gcloud --quiet config set project g-gke-clusters
            gcloud --quiet config set project us-central1-a
            gcloud services enable "compute.googleapis.com" --project="g-gke-clusters"
            gcloud services enable "compute.googleapis.com" --project="g-gke-clusters"
            gcloud compute networks create "dev-playground-network" --project "g-gke-clusters"
      - run:
          name: Create cluster
          command: |
            MASTER_VERSION=$(gcloud container get-server-config --zone="us-central1-a" \
              --format "value(validMasterVersions[0])" 2>/dev/null)
            gcloud container clusters create "dev-playground" \
              --enable-autorepair \
              --machine-type=n1-standard-2 \
              --num-nodes=3 \
              --network="dev-playground-network" \
              --project "g-gke-clusters" \
              --cluster-version="${MASTER_VERSION}" \
              --zone "us-central1-a"
